package id.ngajiyuk.berdoayuk;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;


import com.google.android.gms.ads.MobileAds;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdView;


import java.util.ArrayList;
import java.util.List;

public class BerdoaActivity extends AppCompatActivity {

    private AdView mAdView;
    List<Doa> lstDoa;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_berdoa);
        // Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713
        MobileAds.initialize(this, "ca-app-pub-8539115547513021~6512464543");

        mAdView = findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder().build();
        mAdView.loadAd(adRequest);


        lstDoa = new ArrayList<>();
        lstDoa.add(new Doa("Doa Sebelum Berwudu","نَوَيْتُ الْوُضُوْءَ لِرَفْعِ الْحَدَثِ اْلاَصْغَرِ فَرْضًا لِلّٰهِ تَعَالَى","Nawaitul whudu-a lirof'il hadatsii ashghori fardhon lillaahi ta'aalaa","Artinya :\n"+"\n"+"Saya niat berwudhu untuk menghilangkan hadast kecil fardu (wajib) karena Allah ta'ala",R.drawable.i_sebelum_wudu));
        lstDoa.add(new Doa("Doa Sesudah Berwudu"," اَشْهَدُ اَنْ لاَّاِلَهَ اِلاَّاللهُ وَحْدَهُ لاَشَرِيْكَ لَهُ وَاَشْهَدُ اَنَّ مُحَمَّدًاعَبْدُهُ وَرَسُوْلُهُ. اَللّٰهُمَّ اجْعَلْنِىْ مِنَ التَّوَّابِيْنَ وَاجْعَلْنِىْ مِنَ الْمُتَطَهِّرِيْنَ، وَجْعَلْنِيْ مِنْ عِبَادِكَ الصَّالِحِيْنَ","Asyhadu allaa ilaaha illalloohu wahdahuu laa syariika lahu wa asyhadu anna muhammadan ‘abduhuuwa rosuuluhuu, alloohummaj’alnii minat tawwaabiina waj’alnii minal mutathohhiriina, waj'alnii min 'ibadikash shaalihiina.","Artinya :\n"+"\n"+"Aku bersaksi, tidak ada Tuhan selain Allah Yang Maha Esa, tidak ada sekutu bagi-Nya, dan aku mengaku bahwa Nabi Muhammad itu adalah hamba dan Utusan Allah. Ya Allah, jadikanlah aku dari golongan orang-orang yang bertaubat dan jadikanlah aku dari golongan orang-orang yang suci dan jadikanlah aku dari golongan hamba-hamba Mu yang shaleh",R.drawable.i_sesudah_wudu));
        lstDoa.add(new Doa("Doa Masuk Masjid","اَللّٰهُمَّ افْتَحْ لِيْ اَبْوَابَ رَحْمَتِكَ","Allahummaf tahlii abwaaba rohmatik","Artinya :\n"+"\n"+"Ya Allah, bukalah untukku pintu-pintu rahmat-Mu",R.drawable.i_masuk_masjid));
        lstDoa.add(new Doa("Doa Mendoakan Kedua Orang Tua","اَللّٰهُمَّ اغْفِرْلِيْ وَلِوَالِدَيَّ وَارْحَمْهُمَاكَمَارَبَّيَانِيْ صَغِيْرَا","Alloohummaghfirlii waliwaalidayya warham humma kamaa rabbayaa nii shaghiiraa","Artinya :\n"+"\n"+"Wahai Tuhanku, ampunilah aku dan kedua orang tuaku (Ibu dan Bapakku), sayangilah mereka seperti mereka menyayangiku diwaktu kecil",R.drawable.i_doa_kedua_ortu));
        lstDoa.add(new Doa("Doa Keluar Masjid","اَللّٰهُمَّ اِنِّى اَسْأَلُكَ مِنْ فَضْلِكَ","Allahumma innii asaluka min fadlik","Artinya :\n"+"\n"+"Ya Allah, sesungguhnya aku memohon keutamaan dari-Mu",R.drawable.i_keluar_masjid));
        lstDoa.add(new Doa("Doa Sebelum Membaca Al-Quran","اَللّٰهُمَّ افْتَحْ عَلَىَّ حِكْمَتَكَ وَانْشُرْ عَلَىَّ رَحْمَتَكَ وَذَكِّرْنِىْ مَانَسِيْتُ يَاذَاالْجَلاَلِ وَاْلاِكْرَامِ","Alloohummaftah 'alayya hikmataka wansyur 'alayya rohmataka wa dzakkirnii maanasiitu yaa dzal jalaali wal ikhroomi","Artinya :\n"+"\n"+"Ya Allah bukakanlah hikmahMu padaku, bentangkanlah rahmatMu padaku dan ingatkanlah aku terhadap apa yang aku lupa, wahai Dzat yang memiliki keagungan dan kemuliaan.",R.drawable.i_belajar));
        lstDoa.add(new Doa("Doa Setelah Membaca Al-Quran","اَللّٰهُمَّ ارْحَمْنِىْ بِالْقُرْآنِ. وَاجْعَلْهُ لِىْ اِمَامًا وَنُوْرًا وَّهُدًى وَّرَحْمَةً. اَللّٰهُمَّ ذَكِّرْنِىْ مِنْهُ مَانَسِيْتُ وَعَلِّمْنِىْ مِنْهُ مَاجَهِلْتُ. وَارْزُقْنِىْ تِلاَ وَتَهُ آنَآءَ اللَّيْلِ وَاَطْرَافَ النَّهَارٍ. وَاجْعَلْهُ لِىْ حُجَّةً يَارَبَّ الْعَالَمِيْنَ","Allahummarhamnii bil qur'aani. waj'alhu lii imaaman wa nuuran wa hudan wa rohman. Allahumma dzakkirnii minhu maa nasiitu wa'allimnii minhu maa jahiltu. wazuqnii tilaa watahu aanaa-al laili wa athroofan nahaari. waj'alhu lii hujjatan yaa robbal 'aalamiina.","Artinya :\n"+"\n"+"Ya Allah, rahmatilah aku dengan Al-Quran yang agung, jadikanlah ia bagiku ikutan cahaya petunjuk rahmat. Ya Allah, ingatkanlah apa yang telah aku lupa dan ajarkan kepadaku apa yang tidak aku ketahui darinya, anugerahkanlah padaku kesempatan membacanya pada sebagian malam dan siang, jadikanlah ia hujjah yang kuat bagiku, wahai Tuhan seru sekalian alam",R.drawable.i_belajar));
        lstDoa.add(new Doa("Doa Sebelum Tidur","بِسْمِكَ اللّٰهُمَّ اَحْيَا وَاَمُوْتُ","Bismikallohumma ahya wa amuutu","Artinya :\n"+"\n"+"Dengan menyebut nama-Mu ya Allah, aku hidup dan aku mati",R.drawable.i_tidur));
        lstDoa.add(new Doa("Doa Bangun Tidur","اَلْحَمْدُ ِللهِ الَّذِىْ اَحْيَانَا بَعْدَمَآ اَمَاتَنَا وَاِلَيْهِ النُّشُوْرُ","Alhamdu lillahil ladzii ahyaanaa ba'da maa amaa tanaa wa ilahin nusyuuru","Artinya :\n"+"\n"+"Segala puji bagi Allah yang telah menghidupkan kami sesudah kami mati (membangunkan dari tidur) dan hanya kepada-Nya kami dikembalikan",R.drawable.i_bangun));
        lstDoa.add(new Doa("Doa Mimpi Buruk","اَللّٰهُمَّ إِنّىِ أَعُوْذُ بِكَ مِنْ عَمَلِ الشَّيْطَانِ وَسَيِّئاَتِ اْلأَحْلاَمِ","Allaahumma innii a'uudzubika min 'amalisy syaithaani wa sayyiaatil ahlami","Artinya :\n"+"\n"+"Ya Allah, sesungguhnya aku mohon perlindungan kepada Engkau dari perbuatan setan dan dari mimpi-mimpi yang buruk",R.drawable.i_mimpi));
        lstDoa.add(new Doa("Doa Masuk Kamar Mandi","اَللّٰهُمَّ اِنّىْ اَعُوْذُبِكَ مِنَ الْخُبُثِ وَالْخَبَآئِثِ","Alloohumma Innii a'uudzubika minal khubutsi wal khoaaitsi","Artinya :\n"+"\n"+"Ya Allah, aku berlindung pada-Mu dari godaan syetan  laki-laki dan setan perempuan",R.drawable.i_masuk_wc));
        lstDoa.add(new Doa("Doa Keluar Kamar Mandi","غُفْرَانَكَ الْحَمْدُ ِللهِ الَّذِىْ اَذْهَبَ عَنّى اْلاَذَى وَعَافَانِىْ","Ghufraanaka. Alhamdulillaahil ladzii adzhaba ‘annjil adzaa wa’aafaanii.","Artinya :\n"+"\n"+"Dengan mengharap ampunanMu, segala puji milik Allah yang telah menghilangkan kotoran dari badanku dan yang telah menyejahterakan.",R.drawable.i_keluar_wc));
        lstDoa.add(new Doa("Doa Sebelum Belajar","رَبِّ زِدْنِىْ عِلْمًا وَارْزُقْنِىْ فَهْمًا","robbi zidnii 'ilman warzuqnii fahmaa","Artinya :\n"+"\n"+"Ya Allah, tambahkanlah aku ilmu dan berikanlah aku rizqi akan kepahaman",R.drawable.i_belajar));
        lstDoa.add(new Doa("Doa Sebelum Makan","اَللّٰهُمَّ بَارِكْ لَنَا فِيْمَا رَزَقْتَنَا وَقِنَا عَذَابَ النَّارِ","Alloohumma barik lanaa fiimaa razatanaa waqinaa 'adzaa bannar","Artinya :\n"+"\n"+"Ya Allah, berkahilah kami dalam rezeki yang telah Engkau berikan kepada kami dan peliharalah kami dari siksa api neraka",R.drawable.i_makan));
        lstDoa.add(new Doa("Doa Ketika sedang makan Lupa membaca doa"," بِسْمِ اللهِ فِىِ أَوَّلِهِ وَآخِرِهِ","Bismillaahi fii awwalihi wa aakhirihi","Artinya :\n"+"\n"+"Dengan menyebut nama Allah pada awal dan akhirnya",R.drawable.i_makan));
        lstDoa.add(new Doa("Doa Sesudah Makan","اَلْحَمْدُ ِللهِ الَّذِىْ اَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِيْنَ","Alhamdu lillaahil ladzii ath'amanaa wa saqoonaa wa ja'alnaa muslimiin","Artinya :\n"+"\n"+"Segala puji bagi Allah yang telah memberi makan kami dan minuman kami, serta menjadikan kami sebagai orang-orang islam",R.drawable.i_sesudah_makan));
        lstDoa.add(new Doa("Doa Keluar Rumah","بِسْمِ اللهِ تَوَكَّلْتُ عَلَى اللهِ لاَحَوْلَ وَلاَقُوَّةَ اِلاَّ بِالله","Bismillaahi tawakkaltu 'alalloohi laa hawlaa walaa quwwata illaa bilaahi","Artinya :\n"+"\n"+"Dengan menyebut nama Allah aku bertawakal kepada Allah, tiada daya kekuatan melainkan dengan pertologan Allah.",R.drawable.i_keluar_rumah));
        lstDoa.add(new Doa("Doa Masuk Rumah","اَللّٰهُمَّ اِنّىْ اَسْأَلُكَ خَيْرَالْمَوْلِجِ وَخَيْرَالْمَخْرَجِ بِسْمِ اللهِ وَلَجْنَا وَبِسْمِ اللهِ خَرَجْنَا وَعَلَى اللهِ رَبّنَا تَوَكَّلْنَا","Allahumma innii as-aluka khoirol mauliji wa khoirol makhroji bismillaahi wa lajnaa wa bismillaahi khorojnaa wa'alallohi robbina tawakkalnaa","Artinya :\n"+"\n"+"Ya Allah, sesungguhnya aku mohon kepada-Mu baiknya tempat masuk dan baiknya tempat keluar dengan menyebut nama Allah kami masuk, dan dengan menyebut nama Allah kami keluar dan kepada Allah Tuhan kami, kami bertawakkal",R.drawable.i_masuk_rumah));
        lstDoa.add(new Doa("Doa Naik Kendaraan Darat","سُبْحَانَ الَّذِىْ سَخَّرَلَنَا هَذَا وَمَاكُنَّالَهُ مُقْرِنِيْنَ وَاِنَّآ اِلَى رَبِّنَا لَمُنْقَلِبُوْنَ","Subhaanalladzii sakkhara lanaa hadza wama kunna lahu muqriniin wa-inna ilaa rabbina lamunqalibuun","Artinya :\n"+"\n"+"Maha suci Allah yang telah menundukkan untuk kami (kendaraan) ini. padahal sebelumnya kami tidak mampu untuk menguasainya, dan hanya kepada-Mu lah kami akan kembali ",R.drawable.i_kendaraan_darat));
        lstDoa.add(new Doa("Doa Naik Kendaraan Laut","بِسْمِ اللهِ مَجْرَهَا وَمُرْسَهَآاِنَّ رَبِّىْ لَغَفُوْرٌرَّحِيْمٌ","Bismillaahi majrahaa wa mursaahaa inna robbii laghofuurur rohiim","Artinya :\n"+"\n"+"Dengan nama Allah yang menjalankan kendaraan ini berlayar dan berlabuh, sesungguhnya Tuhanku benar-benar Maha Pengampun lagi Maha Penyayang",R.drawable.i_kendaraan_laut));
        lstDoa.add(new Doa("Doa Masuk Pasar","بِسْمِ اللهِ اَللّٰهُمَّ اِنِّىْ اَسْأَلُكَ خَيْرَهَذَالسُّوْقِ وَخَيْرَ مَافِيْهَا اَللّٰهُمَّ اِنِّىْ اَعُوْذُبِكَ مِنْ شَرِّهَاوَشَرِّمَافِيْهَا","Bismillaahi Allohumma innii as-aluka khoiro haadzas suuqi wa khoiro maa fiihaa, al-loohumma inni a'uudzubika min syarrihaa wa syarrmaa fiiha.","Artinya :\n"+"\n"+"Dengan nama Allah, ya Allah bahwasanya aku memohon kepada-Mu kebaikan pasar ini dan kebaikan yang ada didalamnya, ya Allah bahwasanya aku berlindung diri dengan Engkau dari kejahatan (bencana) pasar ini dan kejahatan yang ada di dalamnya",R.drawable.i_masuk_pasar));
        lstDoa.add(new Doa("Doa Memakai Pakaian Baru","اَلْحَمْدُ لِلّٰهِ الَّذِىْ كَسَانِىْ هَذَا وَرَزَقَنِيْهِ مِنْ غَيْرِ حَوْلٍ مِنِّىْ وَلاَقُوَّةٍ","Alhamdu lillaahil ladzii kasaanii haadzaa wa rozaqoniihi min ghoiri hawlim minni wa laa quwwatin","Artinya :\n"+"\n"+"Segala puji bagi Allah yang memberi aku pakaian ini dan memberi rezeki dengan tiada upaya dan kekuatan dariku",R.drawable.i_keluar_pasar));
        lstDoa.add(new Doa("Doa bercermin","اَلْحَمْدُ ِللهِ كَمَا حَسَّنْتَ خَلْقِىْ  فَحَسِّـنْ خُلُقِىْ","Alhamdulillaahi kamaa hassanta kholqii fahassin khuluqii","Artinya :\n"+"\n"+"Segala puji bagi Allah, baguskanlah budi pekertiku sebagaimana Engkau telah membaguskan rupa wajahku",R.drawable.i_bercermin));
        lstDoa.add(new Doa("Doa berpakaian","بِسْمِ اللهِ اَللّٰهُمَّ اِنِّى اَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَاهُوَ لَهُ وَاَعُوْذُبِكَ مِنْ شَرِّهِ وَشَرِّمَا هُوَلَهُ","Bismillaahi, Alloohumma innii as-aluka min khoirihi wa khoiri maa huwa lahuu wa'a'uu dzubika min syarrihi wa syarri maa huwa lahuu","Artinya :\n"+"\n"+"Dengan nama-Mu yaa Allah akku minta kepada Engkau kebaikan pakaian ini dan kebaikan apa yang ada padanya, dan aku berlindung kepada Engkau dari kejahatan pakaian ini dan kejahatan yang ada padanya",R.drawable.i_pake_baju));
        lstDoa.add(new Doa("Doa melepas pakaian","بِسْمِ اللهِ الَّذِيْ لاَ إِلَهَ إِلَّا هُوَ","Bismillaahil ladzii laa ilaaha illaa huwa","Artinya :\n"+"\n"+"Dengan nama Allah yang tiada Tuhan selain-Nya",R.drawable.i_melepas_pakaian));
        lstDoa.add(new Doa("Doa Menjenguk Orang Sakit","اَللَّهُمَّ رَبَّ النَّاسِ مُذْهِبَ الْبَاسِ اشْفِ أَنْتَ الشَّافِى لاَ شَافِىَ إِلاَّ أَنْتَ ، شِفَاءً لاَ يُغَادِرُ سَقَمًا","Allahumma rabban naas mudzhibal ba'si isyfi antasy-syaafii laa syafiya illaa anta syifaa'an laa yughaadiru saqoman","Artinya :\n"+"\n"+"Ya Allah Wahai Tuhan segala manusia, hilangkanlah penyakitnya, sembukanlah ia. (hanya) Engkaulah yang dapat menyembuhkannya, tidak ada kesembuhan melainkan kesembuhan dariMu, kesembuhan yang tidak kambuh lagi",R.drawable.i_jenguk));
        lstDoa.add(new Doa("Doa Mendapatkan Kabar Gembira"," اَلْحَمْدُلِلّٰهِ رَبِّ الْعَالَمِيْنَ حَمْدًايُوَافِىْ نِعَمَهُ وَيُكَافِىْ مَزِيْدَهُ","Alhamdulillahi rabbil 'alamina hamdan yuwafi ni'mahu wa yukafii maziidah","Artinya :\n"+"\n"+"Segala puji hanya milik Alloh Tuhan seluruh alam, pujian yang menyamai nikmat-Nya dan menandingi keutamaan-Nya",R.drawable.i_senang));
        lstDoa.add(new Doa("Doa Mendengar Kabar Duka","إِنَّا لِلهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ","Innalillahi wa inna ilaihi raji'un","Artinya :\n"+"\n"+"Sesungguhnya kami milik Allah dan kepadaNya kami kembali dan kepada Tuhan kami semua akan kembali",R.drawable.i_kabar_duka));
        lstDoa.add(new Doa("Doa Melihat Ular/Binatang Buas","سَلاَمٌ عَلٰى نُوْحٍ فِى الْعَالَمِيْنَ","Salaamun alaa nuuhin fil 'aalamiin","Artinya :\n"+"\n"+"Kesejahteraan/kedamaian dilimpahkan atas Nuh di seluruh alam",R.drawable.i_ular));
        lstDoa.add(new Doa("Doa Setelah Adzan","اَللّٰهُمَّ رَبَّ هٰذِهِ الدَّعْوَةِ التَّآمَّةِ، وَالصَّلاَةِ الْقَآئِمَةِ، آتِ مُحَمَّدَانِ الْوَسِيْلَةَ وَالْفَضِيْلَةَ وَالشَّرَفَ وَالدَّرَجَةَ الْعَالِيَةَ الرَّفِيْعَةَ وَابْعَثْهُ مَقَامًامَحْمُوْدَانِ الَّذِىْ وَعَدْتَهُ اِنَّكَ لاَتُخْلِفُ الْمِيْعَادَ يَآاَرْحَمَ الرَّحِمِيْنََ","Allaahumma robba haadzihid da'watit taammati wash sholaatil qooimati aati muhammadanil wasiilata wal fadhiilata wasy syarofa wad darajatal 'aaliyatar raofii'ata wab'atshu maqoomam mahmuudanil ladzii wa'adtahu, innaka laa tukhliful mii'aada yaa arhamar roohimiina.","Artinya :\n"+"\n"+"Ya Allah, Tuhan yang mempunyai seruan yang sempurna, dan sholat yang tetap didirikan, karuniailah nabi Muhammad tempat yang luhur, kelebihan, kemuliaan, dan derajat yang tinggi. tempatkanlah dia pada kedudukan yang terpuji seperti yang telah Engkau janjikan. Sesungguhnya Engkau tiada menyalahi janji. wahai dzat yang Maha Penyayang",R.drawable.i_adzan));
        lstDoa.add(new Doa("Doa Keselamatan Dunia Akhirat","  اَللهُمَّ اِنَّا نَسْأَلُكَ سَلاَمَةً فِى الدِّيْنِ وَعَافِيَةً فِى الْجَسَدِ وَزِيَادَةً فِى الْعِلْمِ وَبَرَكَةً فِى الرِّزْقِ وَتَوْبَةً قَبْلَ الْمَوْتِ وَرَحْمَةً عِنْدَ الْمَوْتِ وَمَغْفِرَةً بَعْدَ الْمَوْتِ اَللهُمَّ هَوِّنْ عَلَيْنَا فِى سَكَرَاتِ الْمَوْتِ وَالنَّجَاةَ مِنَ النَّارِ وَالْعَفْوَ عِنْدَ الْحِسَابِ","Alloohumma Innaa Nas-Aluka Salaamatan Fid Diini Wa 'Aafiyatan Fil Jasadi Wa Ziyaadatan Fil 'Ilmi Wa Barokatan Fir Rizqi Wa Taubatan Qoblal Mauti Wa Rohmatan 'Indal Mauti Wa Maghfirotan Ba'dal Mauti , Alloohumma Hawwin 'Alainaa Fii Sakaraatil Mauti Wannajaata Minan Naari Wal 'Afwa 'Indal Hisaabi","Artinya :\n"+"\n"+"Ya Allah kami memohon kepadaMu keselamatan dalam agama, dan kesejahteraan/kesegaran pada tubuh dan penambahan ilmu, dan keberkahan rizqi, serta taubat sebelum mati dan rahmat di waktu mati, dan keampunan sesudah mati. \n"+"Ya Allah, mudahkanlah kami saat pencabutan nyawa, selamat dari api neraka dan mendapat kemaafan ketika amal diperhitungkan",R.drawable.i_sapujagad));
        lstDoa.add(new Doa("Doa Ketika Turun Hujan"," اَللهُمَّ صَيّبًا نَافِعًا ","Allahumma Shoyyiban Naafi'an","Ya Allah semoga (hujan yang Engkau turunkan ini) lebat dan membawa manfaat.",R.drawable.i_hujan));
        lstDoa.add(new Doa("Doa Ketika Melihat Kilat dan Mendengar Petir"," سُبْحَانَ مَنْ يُسَبّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلآئِكَةُ مِنْ خِيْفَتِهِ","Subhaana May Yusabbihur Ro'du Bihamdihi Wal Malaa-Ikatu Min Khiifa Atihi","Artinya :\n"+"\n"+"Maha suci Allah, yang halilintar itu bertasbih dengan memuji kepadaNya demikian juga para malaikat karena takut kepadaNya.",R.drawable.i_petir));
        lstDoa.add(new Doa("Doa Ketika Ada Angin Kencang"," اَللهُمَّ اِنِّىْ اَسْأَلُكَ خَيْرَهَا وَخَيْرَمَا فِيْهَا وَخَيْرَمَآ اَرْسَلْتَ بِهِ، وَاَعُوْذُبِكَ مِنْ شَرِّهَا وَشَرِّمَآ اَرْسَلْتَ بِهِ","Allahumma Inni As-Aluka Khoirohaa Wa Khoiro Maa Fiihaa Wa Khoiro Maa Arsalta Bihi Wa A'uudzu Bika Min Syarrihaa Wa Syariimaa Arsalta Bihi","Artinya :\n"+"\n"+"Ya Allah! aku mohon kepadaMu kebaikannya (angin) dan kebaikannya apa yang ada padanya, dan kebaikan yang dibawanya, dan aku berlindung kepadaMu dari kejahatannya dan kejahatan yang ada padanya dan kejahatan yang dibawanya",R.drawable.i_angin));
        lstDoa.add(new Doa("Doa Tolak Bala"," اَللهُمَّ ادْفَعْ عَنَّاالْغَلَآءَ وَالْبَلَآءَ وَالْوَبَآءَ وَالْفَحْشَاءَ وَالْمُنْكَرَ وَالسُّيُوْفَ الْمُخْتَلِفَةَ وَالشَّدَآئِدَ وَالْمِحَنَ مَاظَهَرَ مِنْهَا وَمَابَطَنَ مِنْ بَلَدِنَا هَذَا خَاصَّةً وَمِنْ بَلْدَانِ الْمُسْلِمِيْنَ عَامَّةً اِنَّكَ عَلَى كُلِّى شَيْئٍ قَدِيْرٌ","Allaahummadfa' 'Annalgholaa-A Walba Laa-A Walwabaa-A Walfahsyaa-A Walmunkaro Wassuyuufalmukhtalifata Wasy-Sya Daa-Ida Walmihana Maadhoharo Minha Wamaabaathona Minbaladinaa Khossotan Wamin Buldaanilmuslimiina 'Aamma Tan Innaka 'Alaa Kulli Syai-In Qodiirun","Artinya :\n"+"\n"+"Ya Allah, hindarkanlaha dari kami kekurangan pangan cobaan hidup penyakit-penyakit wabah, perbuatan-perbuatan keji dan munkar, ancaman-ancaman yang beraneka ragam paceklik-paceklik dan segala ujian, yang lahir maupun batin dari negeri kami ini pada khususnya dan dari seluruh negeri kaum muslimin pada umumnya, karena sesungguhnya Engkau atas segala sesuatu adalah kuasa.",R.drawable.i_bala));
        lstDoa.add(new Doa("Doa Ketika Bersin "," اَلْحَمْدُ ِللهِ","Alhamdulillah","Artinya :\n"+"\n"+"Segala Puji Bagi Allah",R.drawable.i_bersin));
        lstDoa.add(new Doa("Doa Ketika mendengar orang Bersin","  يَرْحَمُكَ اللهُِ","Yarhamukallah","Artinya :\n"+"\n"+"Semoga Allah memberi rahmat kepadamu",R.drawable.i_dengar_bersin));
        lstDoa.add(new Doa("Doa Ketika Telinga Berdenging"," ذَكَرَاللهُ بِخَيْرٍ مِنْ ذَكَرَنِىْ","Dzakarallahu bi khoirin min dzakaronii","Semoga Allah mengingat dengan dengan baik pada orang yang ingat padaku",R.drawable.i_berdenging));
        lstDoa.add(new Doa("Doa Memohon Kesembuhan"," اللّهُمَّ رَبَّ النَّاسِ أَذهِبِ البَأسَ اشفِ أَنتَ الشَّافِيء لَا شِفَاءَ إِلَّا شِفَاوءُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا","Allahuma rabbannas, adz-hibil ba’sa isyfi antasy-syafi laa syifa’a illa syifa’uka, syifa’an laa yughadiru saqaman.","Artinya :\n"+"\n"+"Duhai Allah Tuhan manusia, hilangkanlah rasa sakit ini, sembuhkanlah, Engkaulah Yang Maha Penyembuh, tidak ada kesembuhan yang sejati kecuali kesembuhan yang datang dari-Mu. Yaitu kesembuhan yang tidak meninggalkan komplikasi rasa sakit dan penyakit lain.",R.drawable.i_sembuh));
        lstDoa.add(new Doa("Doa Agar Dijauhkan dari Permusuhan "," اَللهُمَّ لاَتُشْمِتْ بِىْ عَدُوِّىْ وَلاَتَسُؤْبِىْ صَدِيْقِىْ وَلاَ تَجْعَلْ مُصِيْبَتِىْ فِىْ دِيْنِىْ وَلاَ تَجْعَلِ الدُّنْيَآ اَكْبَرَهَمِّىْ وَلاَ تُسَلِّطْ عَلَىَّ مَنْ لاَيَرْحَمُنِىْ يَاحَيُّ يَاقَيُّوْمُ ","ALLOOHUMMA LAA TUSYMIT BII 'ADUWWII WA LAA TASU'BII SHODIIQII WA LAA TAJ'AL MUSIIBATII FII DIINII WA LAA TAJ'ALID DUN-YA AKBARO HAMMII WA LAA TUSALLITH 'ALAYYA MAL LAA YARHAMUNII YA HAYYUU YAA QOYYUUMU","Artinya :\n"+"\n"+"Ya Allah! Janganlah jadikan musuhku gembira karena kesusahanku, dan janganlah jadikan temanku membuat kejahatan terhadapku, dan janganlah jadikan kemalanganku dalam urusan agamaku, dan janganlah jadikan kepentingan dunia menjadi pusat perhatianku, dan janganlah jadikan orang yang tidak berbelas kasihan ber maha raja lela atasku, wahai Tuhan yang hidup yang berdiri sendiri",R.drawable.i_hindari));


        RecyclerView myrv = (RecyclerView) findViewById(R.id.rv_id);
        RecyclerViewAdapter myAdapter = new RecyclerViewAdapter(this,lstDoa);
        myrv.setLayoutManager(new GridLayoutManager(this,2));
        myrv.setAdapter(myAdapter);
    }
}
